export const responses = {
	greetings: [
        "hello",
        "hi",
        "hey",
        "good morning",
        "good afternoon",
        "good evening",
        "greetings",
        "howdy",
        "yo",
        "hi there",
        "hello there",
        "hiya",
        "hey there",
        "how’s it going?",
        "what’s up?",
        "how are you?",
        "how are you doing?",
        "how's everything?",
        "how have you been?",
        "nice to meet you",
        "pleased to meet you",
        "welcome",
        "hiya there",
        "hey ya",
        "howdy there",
        "hey hey",
        "what’s happening?",
        "what’s going on?",
        "long time no see",
        "good to see you",
        "it's been a while",
        "how’s everything going?",
        "how’s your day?",
        "how’s your day going?",
        "how’s your day been?",
        "how’s your day been so far?",
        "how’s your morning?",
        "how’s your afternoon?",
        "how’s your evening?",
        "what have you been up to?",
        "how's life treating you?",
        "how's things?",
        "how’s your week been?",
        "how’s your weekend?",
        "what's new?",
        "what's happening?",
        "what's going on with you?",
        "what's going on in your world?",
        "how's your day treating you?",
        "how's your week treating you?",
        "how's your weekend going?",
        "what have you been doing?",
        "how's everything been?",
        "how’s life?",
        "what's crackin'?",
        "how's your day been going so far?",
        "how’s it hanging?",
        "what's the good word?",
        "what’s new with you?",
        "what’s the latest?",
        "what’s cooking?",
        "how’s everything going with you?",
        "how's your day treating you so far?",
        "how's your day been treating you?",
        "what's up with you?",
        "how’s your day progressing?",
        "how’s your day unfolding?",
        "what's been going on lately?",
        "what's been happening lately?",
        "how are things with you?",
        "how are things going?",
        "how's your day shaping up?",
        "how's your day panning out?",
        "what’s been up?",
        "how’s your day coming along?",
        "how's your day unfolding so far?",
        "what's the news?",
        "what’s cracking?",
        "what’s popping?",
        "what's good?",
        "how’s everything treating you?",
        "what's going on in your life?",
        "what's good with you?",
        "how are things?",
        "how's your day been so far?",
        "what’s the haps?",
        "what’s new with you?",
        "how’s your day been treating you?",
        "how's your day been so far?",
        "how's everything going with you?",
        "how's your day going so far?",
        "what's up?",
        "how have you been?"
    ]
    ,
	help: [
        'help',
        'assistance',
        'support',
        'aid',
        'guidance',
        'helping hand',
        'assisting',
        'aiding',
        'supporting',
        'helpfulness',
        'helping out',
        'assistance needed',
        'support required',
        'helping assistance',
        'assistance required',
        'need help',
        'need assistance',
        'looking for help',
        'looking for assistance',
        'require help',
        'require assistance',
        'seeking help',
        'seeking assistance',
        'helpful',
        'assist',
        'serve',
        'avail',
        'facilitate',
        'advise',
        'backing',
        'back-up',
        'backup',
        'cooperation',
        'helpful hand',
        'helping support',
        'aid and assistance',
        'assistance and support',
        'support and assistance',
        'helping guidance',
        'guidance and support',
        'support and guidance',
        'assistance and guidance',
        'guiding assistance',
        'guiding support',
        'support and help',
        'assistance and help',
        'helping advice',
        'advice and support',
        'support and advice',
        'guidance and advice',
        'advice and assistance',
        'assistance and advice',
        'looking for help and support',
        'need help and assistance',
        'require support and help',
        'seeking assistance and support',
        'helpful assistance',
        'helpful support',
        'helping cooperation',
        'helping back-up',
        'backing and assistance',
        'backing and support',
        'cooperative assistance',
        'cooperative support',
        'assistance cooperation',
        'support cooperation',
        'helping cooperation',
        'helpful cooperation',
        'helping aid',
        'helping advice',
        'need advice',
        'need backing',
        'need aid',
        'need cooperation',
        'looking for advice',
        'looking for backing',
        'looking for aid',
        'looking for cooperation',
        'require advice',
        'require backing',
        'require aid',
        'require cooperation',
        'seeking advice',
        'seeking backing',
        'seeking aid',
        'seeking cooperation',
        'helpful advice',
        'helpful backing',
        'helpful aid',
        'helpful cooperation'
    ]
,    
	
	services: [
		'services',
		'what do you offer',
		'what can you do',
		'offered services',
		'service offerings',
		'available services',
		'what services do you provide',
		'list of services',
		'types of services',
		'service list',
		'service options',
		'services available',
		'services provided',
		'what services are offered',
		'service catalog',
		'service menu',
		'services offered',
		'service portfolio',
		'range of services',
		'service lineup',
		'service selection',
		'service repertoire',
		'service spectrum',
		'service inventory',
		'service range',
		'service capabilities',
		'service offerings list',
		'services provided list',
		'service assortment',
		'service lineup',
		'service provision',
		'service collection',
		'service variety',
		'service package',
		'service options list',
		'services catalog',
		'service availability',
		'service details',
		'services list',
		'service menu options',
		'available service list',
		'service offerings menu',
		'services provided menu',
		'service portfolio list',
		'service options available',
		'service offerings catalog',
		'service range list',
		'service offerings menu',
		'service inventory list',
		'service assortment list',
		'service repertoire list',
		'service spectrum list',
		'service capabilities list',
		'service provision list',
		'service collection list',
		'service variety list',
		'service package list',
		'service options menu',
		'services catalog list',
		'service availability list',
		'service details list',
		'services list menu',
		'service options catalog',
		'available service options',
		'service offerings menu list',
		'services provided menu list',
		'service portfolio menu',
		'service options catalog list',
		'services provided catalog',
		'service repertoire menu',
		'service capabilities menu',
		'service provision menu',
		'service variety menu',
		'service options collection',
		'service options variety',
		'service options inventory',
		'service options range',
		'service options spectrum',
		'service options repertoire',
		'service options capabilities',
		'service options provision',
		'service options collection list',
		'service options variety list',
		'service options inventory list',
		'service options range list',
		'service options spectrum list',
		'service options repertoire list',
		'service options capabilities list',
		'service options provision list'
	],
	pricing: [
		'pricing',
		'how much',
		'cost',
		'charge',
		'project price',
		'how much for web development?',
		'web development price',
		'what is the price?',
		'quote',
		'budget',
		'rates',
		'pricing information',
		'price range',
		'pricing details',
		'estimate',
		'cost estimation',
		'quotation',
		'price tag',
		'fee',
		'service fee',
		'web development cost',
		'development charges',
		'cost of services',
		'project estimation',
		'pricing plan',
		'web development rates',
		'cost breakdown',
		'how expensive',
		'expense',
		'rate card',
		'cost inquiry',
		'project budget',
		'expense estimation',
		'quote for web development',
		'web development quotation',
		'cost calculation',
		'project expense',
		'pricing quote',
		'charge details',
		'price inquiry',
		'project costing',
		'pricing structure',
		'cost estimate',
		'pricing scheme',
		'price quote',
		'project pricing',
		'development cost',
		'service pricing',
		'development pricing',
		'charge rate',
		'budget inquiry',
		'pricing policy',
		'cost quote',
		'development fee',
		'service cost',
		'charge estimation',
		'cost for development',
		'development budget',
		'cost quote for web development',
		'web development expense',
		'charge quote',
		'project charge',
		'web development budget',
		'pricing request',
		'web development cost inquiry',
		'development quote',
		'cost plan',
		'price estimate',
		'service charge',
		'price inquiry for web development',
		'service quote',
		'cost for web development',
		'pricing rate',
		'development quotation',
		'charge calculation',
		'web development cost estimate',
		'price estimate for web development',
		'project cost',
		'web development budget inquiry',
		'development pricing information',
		'pricing calculation',
		'price details',
		'project quotation',
		'web development pricing details',
		'development cost inquiry',
		'cost calculation for web development',
		'service pricing for web development',
		'charge inquiry',
		'web development expense estimate',
		'cost estimate for web development',
		'development pricing quote',
		'pricing estimation',
		'cost estimate inquiry',
		'web development charge',
		'pricing query',
		'web development service cost',
		'charge quote for web development',
		'web development price inquiry',
		'web development service pricing',
		'development cost estimate',
		'project cost estimation',
		'web development cost calculation',
		'charge rate for web development',
		'pricing inquiry',
		'web development service charge',
		'web development pricing inquiry',
		'project pricing inquiry',
		'web development pricing estimate'
	],
	'thank you': ['thank you', 'thanks'],
	contact: [
		'contact',
		'provide me your contact',
		'can you give me contact details?',
		'reach out',
		'get in touch',
		'connect with',
		'reach me',
		'contact information',
		'contact details',
		'get hold of me',
		'drop me a line',
		'send me a message',
		'message me',
        'location',
		'send an email',
		'hit me up',
		'shoot me an email',
		'drop a message',
		'reach out to me',
		'drop a line',
		'send a message',
		'send a note',
		'get in contact',
		'reach me via',
		'contact me through',
		'contact me via',
		'get a hold of',
		'make contact',
		'establish contact',
		'contact me for details',
		'get a hold of me via',
		'shoot me a message',
		'connect via',
		'communicate with me',
		'get a hold of me for more information',
		'send me an inquiry',
		'inquire with me',
		'get a hold of me for inquiries',
		'shoot me a quick note',
		'drop me a quick message',
		'drop me a quick line',
		'reach out to me for further details',
		'send me a quick email',
		'drop me a quick email',
		'get in contact with me for additional information',
		'reach out to me for any questions',
		'contact me directly',
		'send a quick message my way',
		'drop me a message for assistance',
		'shoot me a quick email',
		'send me a quick message for assistance',
		'reach out to me directly',
		'contact me ASAP',
		'reach me out for support',
		'send me a direct message',
		'hit me up for inquiries',
		'shoot me a quick message for inquiries',
		'drop me a message for further details',
		'reach out to me for inquiries',
		'send me a message for more information',
		'get a hold of me for assistance',
		'contact me for assistance',
		'drop me a line for assistance',
		'shoot me a message for support',
		'reach out to me for support',
		'contact me for support',
		'get in touch with me for help',
		'send me an email for help',
		'shoot me a message for help',
		'reach out to me for help',
		'drop me a message for help',
		'contact me for help',
		'reach out to me for assistance',
		'send me a message for assistance',
		'drop me a line for help',
		'shoot me a message for assistance',
		'get in touch with me for assistance',
		'send me an email for assistance',
		'reach out to me directly for assistance',
		'contact me directly for assistance',
		'get a hold of me for support',
		'send me a message for support',
		'drop me a line for support',
		'shoot me a message for support',
		'reach out to me for support',
		'contact me for support',
		'get in touch with me for support',
		'send me an email for support',
		'reach out to me directly for support',
		'contact me directly for support',
		'reach me out for inquiries',
		'send me an inquiry message',
		'shoot me an inquiry email',
		'drop me an inquiry message',
		'reach out to me for further assistance',
		'get a hold of me for further assistance',
		'contact me for further assistance',
		'send me a message for further assistance',
		'shoot me a message for further assistance',
		'reach out to me directly for further assistance',
		'contact me directly for further assistance',
		'reach out to me for additional assistance',
		'get in touch with me for additional assistance',
		'email',
		'phone'
	]
};

export let responseMessages = {
	greetings: '<p>Hello! How can I assist you today?</p>',
	help: '<p>You can ask me about our services, pricing, contact, showcases and more.</p>',
	services: `<p>"I specialize in full-stack development utilizing SvelteKit and Pocketbase, alongside expertise in Chrome extension development, UI/UX design, and creating Figma plugins. To enhance client visibility and trust, I also conduct API reverse engineering."</p>`,
	pricing: '<p>My  pricing depends on the service. For web development, prices start at $1000.</p>',
	'thank you': "<p>You're welcome! Feel free to ask anything else.</p>",
	contact: `

    <p>
    Email: business.aleenbhandari@gmail.com<br>
    Phone: +977-9807038534<br>
    Location: Nepal, Dharan<br>
    <a href="/contact">Contact Me</a>
    </p>
    `
};
