export const responses = {
	greetings: ['hello', 'hi', 'hey'],
	help: ['help', 'assistance'],
	services: ['services', 'what do you offer', 'what can you do'],
	pricing: ['pricing', 'how much', 'cost'],
	'thank you': ['thank you', 'thanks'],
	contact: [
		'contact',
		'provide me your contact',
		'can you give me contact details?',
		'reach out',
		'get in touch',
		'connect with',
		'reach me',
		'contact information',
		'contact details',
		'get hold of me',
		'drop me a line',
		'send me a message',
		'message me',
		'send an email',
		'hit me up',
		'shoot me an email',
		'drop a message',
		'reach out to me',
		'drop a line',
		'send a message',
		'send a note',
		'get in contact',
		'reach me via',
		'contact me through',
		'contact me via',
		'get a hold of',
		'make contact',
		'establish contact',
		'contact me for details',
		'get a hold of me via',
		'shoot me a message',
		'connect via',
		'communicate with me',
		'get a hold of me for more information',
		'send me an inquiry',
		'inquire with me',
		'get a hold of me for inquiries',
		'shoot me a quick note',
		'drop me a quick message',
		'drop me a quick line',
		'reach out to me for further details',
		'send me a quick email',
		'drop me a quick email',
		'get in contact with me for additional information',
		'reach out to me for any questions',
		'contact me directly',
		'send a quick message my way',
		'drop me a message for assistance',
		'shoot me a quick email',
		'send me a quick message for assistance',
		'reach out to me directly',
		'contact me ASAP',
		'reach me out for support',
		'send me a direct message',
		'hit me up for inquiries',
		'shoot me a quick message for inquiries',
		'drop me a message for further details',
		'reach out to me for inquiries',
		'send me a message for more information',
		'get a hold of me for assistance',
		'contact me for assistance',
		'drop me a line for assistance',
		'shoot me a message for support',
		'reach out to me for support',
		'contact me for support',
		'get in touch with me for help',
		'send me an email for help',
		'shoot me a message for help',
		'reach out to me for help',
		'drop me a message for help',
		'contact me for help',
		'reach out to me for assistance',
		'send me a message for assistance',
		'drop me a line for help',
		'shoot me a message for assistance',
		'get in touch with me for assistance',
		'send me an email for assistance',
		'reach out to me directly for assistance',
		'contact me directly for assistance',
		'get a hold of me for support',
		'send me a message for support',
		'drop me a line for support',
		'shoot me a message for support',
		'reach out to me for support',
		'contact me for support',
		'get in touch with me for support',
		'send me an email for support',
		'reach out to me directly for support',
		'contact me directly for support',
		'reach me out for inquiries',
		'send me an inquiry message',
		'shoot me an inquiry email',
		'drop me an inquiry message',
		'reach out to me for further assistance',
		'get a hold of me for further assistance',
		'contact me for further assistance',
		'send me a message for further assistance',
		'shoot me a message for further assistance',
		'reach out to me directly for further assistance',
		'contact me directly for further assistance',
		'reach out to me for additional assistance',
		'get in touch with me for additional assistance',
        'email',
        'phone'
	]
};

export let responseMessages = {
	greetings: '<p>Hello! How can I assist you today?</p>',
	help: '<p>You can ask me about our services, pricing, and more.</p>',
	services: `<p>"I specialize in full-stack development utilizing SvelteKit and Pocketbase, alongside expertise in Chrome extension development, UI/UX design, and creating Figma plugins. To enhance client visibility and trust, I also conduct API reverse engineering."</p>`,
	pricing: '<p>Our pricing depends on the service. For web development, prices start at $500.</p>',
	'thank you': "<p>You're welcome! Feel free to ask anything else.</p>",
    contact: `

    <p>
    Email: business.aleenbhandari@gmail.com<br>
    Phone: +977-9807038534<br>
    Location: Nepal, Dharan
    </p>
    `
};
